version: "2"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    env_file: ./.env
    environment:
      - NODE_ENV=development
      - PORT=3000
    ports:
      - "4002:3000"
    restart: always
    container_name: prep-legacy
