version: '2'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env
    command: npm start
    environment:
      NODE_ENV: development
      PORT: 3000
    restart: always
    container_name: prep-app
    volumes:
      - "./:/usr/src/prep-app"
